/*
 * com.connect.client.Phone
 *
 * Generated By LaravelConnect for Android on 2018-06-01 21:15:32
 *
 */
 
 
package com.connect.client;

import java.util.*;
import io.square1.laravelConnect.*;
import android.content.Context;
import io.square1.laravelConnect.model.*;
import io.square1.laravelConnect.client.Sort;
import io.square1.laravelConnect.client.ApiRequest;
import io.square1.laravelConnect.requests.LaravelRequest;
import io.square1.laravelConnect.client.LaravelConnectClient;
import io.square1.laravelConnect.client.results.ResultObj;




public class Phone extends BaseModel {

    public final static String PRIMARY_KEY = "id";
    
    private  ModelProperty<String> _label;
    private  ModelProperty<String> _number;
    private  ModelProperty<Integer> _user_id;
    private  ModelProperty<Date> _created_at;
    private  ModelProperty<Date> _updated_at;
        
    private  ModelOneRelation<User> _user;
    
    public Phone() {
      super(PRIMARY_KEY);
      _label = (ModelProperty<String>)addProperty("label",String.class);
    _number = (ModelProperty<String>)addProperty("number",String.class);
    _user_id = (ModelProperty<Integer>)addProperty("user_id",Integer.class);
    _created_at = (ModelProperty<Date>)addProperty("created_at",Date.class);
    _updated_at = (ModelProperty<Date>)addProperty("updated_at",Date.class);
     
      
      _user = (ModelOneRelation<User>)addRelation("user","user_id", User.class);
     
      }

    public ModelProperty<String> getLabel(){
        return this._label;
}

public void setLabel(String value){
    this._label.setValue(value);
}
public ModelProperty<String> getNumber(){
        return this._number;
}

public void setNumber(String value){
    this._number.setValue(value);
}
public ModelProperty<Integer> getUserId(){
        return this._user_id;
}

public void setUserId(Integer value){
    this._user_id.setValue(value);
}
public ModelProperty<Date> getCreatedAt(){
        return this._created_at;
}

public void setCreatedAt(Date value){
    this._created_at.setValue(value);
}
public ModelProperty<Date> getUpdatedAt(){
        return this._updated_at;
}

public void setUpdatedAt(Date value){
    this._updated_at.setValue(value);
}
    

    public ModelOneRelation<User> getUser(){
        return this._user;
}


 
    
   public static ModelList list(){
        return ModelList.listForModel(Phone.class);
    }

    public static ApiRequest get(int id, LaravelConnectClient.Observer observer){

        return BaseModel.get( Phone.class, id, observer);
    }
    
       
    
    public static final String getModelPath(){
      return "phone";
    }
}